#!/bin/bash
#Format CAWCR data to gx1 grid.
#read year

echo 'What year do you want to format? (YYYY)'

read year

VAR1="Hello,"
VAR2=" World"
VAR3="$VAR1$VAR2"
echo "$VAR3"
gridded="gridded_ww3.glob_24m."
file_name="$gridded$year"
echo "$file_name"

for file in `find /Users/noahday/github/cice-dirs/input -name 'file_name*'`
#"gridded_ww3.glob_24m.2007*"`
do
  filetemp=$(basename $file)
  filetemp="${filetemp#*.}"
  filetemp="${filetemp#*.}"
  filetemp="${filetemp%.*}"
  filetemp="ww3_${filetemp}.nc"
  echo "$file"
  echo "Starting $filetemp"

  #cdo remapbil,gridgx1.nc $file $filetemp
done
echo "Formatting complete."
